### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by cmaslen** [zyborg/Zyborg.Vault#1]
Hi,
The module doesn't appear to install on a Windows 10 machine.
Regards,
Christian.

**Comment by ebekker** [comment]
Can you provide more detail about what problems you're running into?  The module was developed and tested on Windows 10.

**Comment by cmaslen** [comment]
Hi @ebekker ,

Thanks for the response. The following is running the install on verbose mode...

<pre>
    PS C:\WINDOWS\system32> Install-Module -Name Zyborg.Vault -Verbose
    VERBOSE: Using the provider 'PowerShellGet' for searching packages.
    VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
    VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
    VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is
'NuGet'.
    VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Zyborg.Vault'' for ''.
    VERBOSE: Total package yield:'1' for the specified package 'Zyborg.Vault'.
    VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
    VERBOSE: The specified Location is 'https://www.myget.org/F/zyborg-stage/api/v3/index.json' and
PackageManagementProvider is 'NuGet'.
    VERBOSE: Retry downloading 'https://www.myget.org/F/zyborg-stage/api/v3/index.json/FindPackagesById()?id='FoooBarr''
for '2' more times
    VERBOSE: Retry downloading 'https://www.myget.org/F/zyborg-stage/api/v3/index.json/FindPackagesById()?id='FoooBarr''
for '1' more times
    VERBOSE: Retry downloading 'https://www.myget.org/F/zyborg-stage/api/v3/index.json/FindPackagesById()?id='FoooBarr''
for '0' more times
    WARNING: Unable to resolve package source 'https://www.myget.org/F/zyborg-stage/api/v3/index.json'.
    VERBOSE: Total package yield:'0' for the specified package 'Zyborg.Vault'.
    VERBOSE: Skipping installed module Zyborg.Vault 0.6.0.36.
</pre>

**Comment by ebekker** [comment]
@cmaslen -- did you register a default "zyborg-stage" PowerShell repository?  It looks like it's trying to search there.  If you have multiple repos defined, you can specify the exact one to pull from.  This will specify to use the default PowerShell Gallery which should be registered out-of-the-box:

```PowerShell
PS C:\Users\Administrator> Install-Module Zyborg.Vault -Repository PSGallery -Verbose
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Zyborg.Vault'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'Zyborg.Vault'.
VERBOSE: Performing the operation "Install-Module" on target "Version '0.6.0.36' of module 'Zyborg.Vault'".
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'Zyborg.Vault' with version '0.6.0.36' from the repository 'https://www.powershellgallery.com/api/v2/'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Zyborg.Vault'' for ''.
VERBOSE: InstallPackage' - name='Zyborg.Vault', version='0.6.0.36',destination='C:\Users\Administrator\AppData\Local\Temp\2\544754512'
VERBOSE: DownloadPackage' - name='Zyborg.Vault', version='0.6.0.36',destination='C:\Users\Administrator\AppData\Local\Temp\2\544754512\Zyborg.Vault\Zyborg.Vault.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Zyborg.Vault/0.6.0.36'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Zyborg.Vault/0.6.0.36'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Zyborg.Vault/0.6.0.36'.
VERBOSE: Completed downloading 'Zyborg.Vault'.
VERBOSE: Hash for package 'Zyborg.Vault' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='Zyborg.Vault', version='0.6.0.36',destination='C:\Users\Administrator\AppData\Local\Temp\2\544754512'
VERBOSE: Catalog file 'Zyborg.Vault.cat' is not found in the contents of the module 'Zyborg.Vault' being installed.
VERBOSE: Module 'Zyborg.Vault' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\Zyborg.Vault\0.6.0.36'.
```

**Comment by ebekker** [comment]
I'm hoping my last comment addressed your issue since I didn't see any response since.
