### ISSUE TITLE
Authentication with RoleID and SecretID

### ISSUE THREAD

**Issue by luiXIV** [zyborg/Zyborg.Vault#5]
Any possibility to authenticate with role and secretID? (approle method)

**Comment by peimanja** [comment]
Yea basically other `vault login` methods are not supported.

**Comment by hognevevle** [comment]
So, in other words, approle authentication is not supported?

**Comment by ebekker** [comment]
Unfortunately, this library is low priority for me at this time, so unlikely any changes will be forthcoming, but PRs are always welcome.

**Comment by luiXIV** [comment]
Thank you
