### ISSUE TITLE
Newer Feature Support

### ISSUE THREAD

**Issue by FunkyDisko77** [zyborg/Zyborg.Vault#6]
There doesn't appear to be any support for features like namespaces. Are there any plans for this to be updated to add support for newer features?

**Comment by ebekker** [comment]
Unfortunately, this library is low priority for me at this time, so unlikely any changes will be forthcoming, but PRs are always welcome.

**Comment by FunkyDisko77** [comment]
That's fair. Thanks for the quick reply, at least!
